drop table if exists users CASCADE;
create table users
(
    id         bigint generated by default as identity,
    email      varchar(50)  not null,
    name       varchar(50)  not null,
    password   varchar(255) not null,
    phone      varchar(20),
    point      integer default 0,
    rank       varchar(255),
    created_at timestamp,
    updated_at timestamp,
    primary key (id)
)
