drop table if exists users CASCADE;
create table users
(
    user_id    bigint generated by default as identity,
    email      varchar(50)  not null,
    name       varchar(50)  not null,
    password   varchar(255) not null,
    phone      varchar(20),
    point      integer default 0,
    membership varchar(255),
    created_at timestamp,
    updated_at timestamp,
    primary key (user_id)
)
